--- #YAML:1.0
name:               Religion-Bible-Regex-Config
version:            0.6
abstract:           Creates a configuration object for the Religion::Bible::Regex objects from a YAML file.
author:
    - Daniel Holmlund <holmlund.dev@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Perl::Critic:  0
    Test::Base:    0
    Test::Deep:    0
    Test::More:    0
    version:       0
    YAML:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
